// angular-project/src/app/app.component.ts
import { Component } from '@angular/core';

@Component({
  selector: 'app-root',
  templateUrl: './app.component.html',
  styleUrls: ['./app.component.css'],
})
export class AppComponent {
  //for Settlement
  formTitle: string = 'Pass React Props to angular';

  // SearchBox
  searchTitle: string = 'Search the Files';
  onSubmit(event: any) {
    console.log('Save event triggered:', event.detail);
  }

  // MaskedInput
  label: string = 'Phone Number';
}

<aw-search-box
  [attr.searchTitle]="searchTitle"
  (submit)="onSubmit($event)"
></aw-search-box>

<aw-text-field [attr.label]="label"></aw-text-field>
<aw-settlement [attr.formTitle]="formTitle"></aw-settlement>
<aw-rich-text-editor></aw-rich-text-editor>

// react-project/src/App.tsx
import { RichTextEditor } from "richTextEditor";
import "./App.css";
import AppRouter from "./AppRouter";
import { Settlement } from "evaluation/evaluation-details/settlement";
import { SearchBox } from "common-ui/search-box/SearchBox";
import { MaskedInput } from "common-ui/search-box/TextField";
import { TabValue } from "tabs/TabValue";

interface IAppProps {
  baseHref?: string;
}
export default function App({ baseHref }: IAppProps) {
  return (
    <div className="App">
      <SearchBox
        searchTitle="Search"
        onSubmit={(value) => console.log(value)}
      />
      <TabValue />
      <MaskedInput label="Phone Number" />
      <Settlement formTitle="Settlment Amont with Area" />
      <RichTextEditor />
      <AppRouter />
    </div>
  );
}
